// frontend/src/pages/CarForm.tsx
import React, { useEffect, useState, useRef } from 'react'
import api from '../api'

interface CarFormProps {
  id?: string | null
  onClose: () => void
  onSaved: () => void
}

export default function CarForm({ id, onClose, onSaved }: CarFormProps) {
  const [form, setForm] = useState<any>({
    model: '',
    version: '',
    year: '',
    mileage: '',
    price: '',
    description: '',
    brandId: '',
    storeId: '',
    images: [] as (File | string)[]
  })
  const fileInputRef = useRef<HTMLInputElement | null>(null)

  const onFilesAdded = (items: Array<File | string>) => {
    setForm((s:any) => ({ ...s, images: [...(s.images || []), ...items] }))
  }

  const removeImageAt = (index: number) => {
    setForm((s:any) => ({ ...s, images: (s.images || []).filter((_:any, i:number) => i !== index) }))
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    const files = Array.from(e.dataTransfer.files || [])
    if (files.length) onFilesAdded(files)
  }

  const handlePickFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || [])
    if (files.length) onFilesAdded(files)
  }
  const [brands, setBrands] = useState<any[]>([])
  const [stores, setStores] = useState<any[]>([])
  const [loading, setLoading] = useState(false)
  const [message, setMessage] = useState<{ type: 'success' | 'error', text: string } | null>(null)
  const [showResultModal, setShowResultModal] = useState(false)

  useEffect(() => {
    api.get('/brands').then(r => setBrands(r.data.data || []))
    api.get('/stores').then(r => setStores(r.data.data || []))
    if (id) {
      api.get(`/cars/${id}`).then(r => setForm(r.data.data || form))
    }
  }, [id])

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      setLoading(true)
      setMessage(null)
      const formData = new FormData()

      Object.entries(form).forEach(([k, v]) => {
        if (k === 'images') return 
        formData.append(k, v as string)
      })


      const files: File[] = []
      const existing: string[] = []
      const imgs = (form.images || []) as (File | string)[]
      imgs.forEach((it:any) => {
        if (typeof it === 'string') existing.push(it)
        else files.push(it as File)
      })


      files.forEach(f => formData.append('images', f))
     
      if (existing.length) formData.append('imagesExisting', JSON.stringify(existing))

      if (id) await api.put(`/cars/${id}`, formData)
      else await api.post('/cars', formData)

      const successText = id ? 'Edição realizada com sucesso' : 'Cadastro concluído com sucesso'
      setMessage({ type: 'success', text: successText })
      setShowResultModal(true)
      onSaved()

      setTimeout(() => { setShowResultModal(false); onClose() }, 900)
    } catch (e) {
      setMessage({ type: 'error', text: 'Falha ao salvar' })
      setLoading(false)
    }
  }

  const remove = async () => {
    if (!id) return
    if (!confirm('Confirma exclusão?')) return
    try {
      setLoading(true)
      await api.delete(`/cars/${id}`)
      setMessage({ type: 'success', text: 'Exclusão realizada com sucesso' })
      setShowResultModal(true)
      onSaved()
      setTimeout(() => { setShowResultModal(false); onClose() }, 900)
    } catch {
      setMessage({ type: 'error', text: 'Falha ao excluir' })
      setLoading(false)
    }
  }

  return (
    <div className="modal-overlay">
      <style>{`
        .modal-overlay {
          position: fixed;
          inset: 0;
          background: rgba(0,0,0,0.4);
          display: flex;
          justify-content: center;
          align-items: center;
          z-index: 1000;
        }
        .card {
          background: #fff;
          border-radius: 12px;
          padding: 24px;
          width: 500px;
          max-height: 70vh;
          overflow-y: auto;
          box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        }
        .field {
          display: flex;
          flex-direction: column;
          margin-bottom: 16px;
        }
        .field label {
        color: #010101ff;
          font-weight: 600;
          margin-bottom: 6px;
        }
        .field input,
        .field select,
        .field textarea {
          border: 1px solid #010101ff;
          border-radius: 6px;
          padding: 10px;
          font-size: 14px;
        }
        .field textarea {
          resize: vertical;
          min-height: 80px;
        }
        .footer-actions {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-top: 20px;
        }
        .btn {
          border: none;
          padding: 10px 38px;
          border-radius: 25px;
          font-size: 14px;
          cursor: pointer;
          font-weight: 600;
        }
        .btn.cancel {
          background: #f5f5f5;
          color: #333;
        }
        .btn.save {
          background: #007f56;
          color: #fff;
          padding: 8px 45px;
        }
        .btn.danger {
          background: #e74c3c;
          color: #fff;
        }
        .result-modal-overlay {
          position: absolute;
          inset: 0;
          display: flex;
          align-items: center;
          justify-content: center;
          pointer-events: none;
        }
        .result-modal {
          pointer-events: all;
          background: #fff;
          padding: 18px 22px;
          border-radius: 10px;
          box-shadow: 0 6px 18px rgba(0,0,0,0.16);
          text-align: center;
          min-width: 260px;
        }

        /* upload area */
        .upload-area {
          border: 2px dashed #cfcfcf;
          border-radius: 12px;
          padding: 14px;
          min-height: 110px;
          display: flex;
          align-items: center;
          box-sizing: border-box;
          background: #fff;
        }
        .upload-area .thumbs {
          display: flex;
          gap: 12px;
          flex-wrap: wrap;
          align-items: center;
        }
        .upload-area .thumb {
          width: 100px;
          height: 80px;
          border-radius: 8px;
          overflow: hidden;
          position: relative;
          background: #f6f6f6;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 2px 6px rgba(0,0,0,0.06);
        }
        .upload-area .thumb img { width: 100%; height: 100%; object-fit: cover; display: block; }
        .upload-area .thumb.add {
          cursor: pointer;
          border: 1px solid #e6e6e6;
          display: inline-flex;
          align-items: center;
          justify-content: center;
        }
        .upload-area .thumb .plus { font-size: 28px; color: #7d7d7d; }
        .upload-area .thumb .remove {
          position: absolute;
          top: 6px;
          right: 6px;
          background: #ffffffcc;
          border: none;
          width: 22px;
          height: 22px;
          border-radius: 50%;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 1px 4px rgba(0,0,0,0.12);
          cursor: pointer;
        }
      `}</style>

      <div className="card">
        {message && !showResultModal && (
          <div style={{ marginBottom: 12, padding: 10, borderRadius: 8, background: message.type === 'success' ? '#e6ffef' : '#ffecec', color: message.type === 'success' ? '#007f56' : '#a40000' }}>
            {message.text}
          </div>
        )}

        {showResultModal && message && (
          <div className="result-modal-overlay">
            <div className="result-modal">
              <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 6 }}>{message.text}</div>
              <div style={{ fontSize: 13, color: '#444' }}>{message.type === 'success' ? 'Operação concluída com sucesso.' : 'Ocorreu um problema.'}</div>
            </div>
          </div>
        )}
        <form onSubmit={submit}>
          <div className="field">
            <label>Marca</label>
            <select
              value={form.brandId}
              onChange={e => setForm({ ...form, brandId: e.target.value })}
            >
              <option value="">Selecione a marca</option>
              {brands.map(b => (
                <option key={b.id} value={b.id}>
                  {b.name}
                </option>
              ))}
            </select>
          </div>

          <div className="field">
            <label>Loja</label>
            <select
              value={form.storeId}
              onChange={e => setForm({ ...form, storeId: e.target.value })}
            >
              <option value="">Selecione a loja</option>
              {stores
                .filter(s => s.brandId.toString() === form.brandId.toString())
                .map(s => (
                  <option key={s.id} value={s.id}>
                    {s.name}
                  </option>
                ))}
            </select>
          </div>

          <div className="field">
            <label>Modelo</label>
            <input
              value={form.model}
              onChange={e => setForm({ ...form, model: e.target.value })}
              placeholder="Informe o modelo"
            />
          </div>

          <div className="field">
            <label>Versão</label>
            <input
              value={form.version}
              onChange={e => setForm({ ...form, version: e.target.value })}
              placeholder="Informe a versão"
            />
          </div>

          <div className="field">
            <label>Ano Fabricação/Modelo</label>
            <input
              value={form.year}
              onChange={e => setForm({ ...form, year: e.target.value })}
              placeholder="Ex: 2018/2019"
            />
          </div>

          <div className="field">
            <label>Quilometragem</label>
            <input
              value={form.mileage}
              onChange={e => setForm({ ...form, mileage: e.target.value })}
              placeholder="Informe a quilometragem"
            />
          </div>

          <div className="field">
            <label>Valor</label>
            <input
              value={form.price}
              onChange={e => setForm({ ...form, price: e.target.value })}
              placeholder="Informe o valor"
            />
          </div>

          <div className="field">
            <label>Descrição</label>
            <textarea
              value={form.description}
              onChange={e => setForm({ ...form, description: e.target.value })}
              placeholder="Descrição"
            />
          </div>

          <div className="field">
            <label>Upload imagens</label>
            <div
              className="upload-area"
              onDrop={handleDrop}
              onDragOver={e => e.preventDefault()}
            >
              <div className="thumbs">
                {(form.images || []).map((it:any, i:number) => (
                  <div key={i} className="thumb">
                    <img src={typeof it === 'string' ? it : URL.createObjectURL(it)} alt={`img-${i}`} />
                    <button type="button" className="remove" onClick={() => removeImageAt(i)}>✕</button>
                  </div>
                ))}

                <div className="thumb add" onClick={() => fileInputRef.current?.click()}>
                  <div className="plus">+</div>
                </div>
              </div>
              <input ref={fileInputRef} type="file" multiple style={{ display: 'none' }} onChange={handlePickFiles} />
            </div>
          </div>

          <div className="footer-actions">
            <div>
              {id ? (
                <button
                  type="button"
                  className="btn danger"
                  onClick={remove}
                >
                  Excluir
                </button>
              ) : (
                <div style={{ width: 92 }} />
              )}
            </div>
            <div style={{ display: 'flex', gap: 12 }}>
              <button type="button" className="btn cancel" onClick={onClose} disabled={loading}>
                Cancelar
              </button>
              <button className="btn save" type="submit" disabled={loading}>
                {loading ? 'Salvando...' : 'Salvar'}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}

// frontend/src/app/features/cars/car-form.component.ts

import { Component, EventEmitter, Input, OnInit, Output, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, NgForm } from '@angular/forms';
import { CarsService } from './cars.service';

@Component({
  selector: 'app-car-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './car-form.component.html',
  styleUrls: ['./car-form.component.css']
})
export class CarFormComponent implements OnInit {
  @Input() id: string | null = null;
  @Output() onClose = new EventEmitter<void>();
  @Output() onSaved = new EventEmitter<void>();
  @Output() onMessage = new EventEmitter<{type:'success'|'error', text:string}>();

  form: any = { model: '', version: '', year: '', mileage: '', price: '', description: '', brandId: '', storeId: '', images: [] };
  brands: any[] = [];
  stores: any[] = [];
  allStores: any[] = [];
  brandsLoaded = false;
  storesLoaded = false;
  loading = false;
  message: any = null;
  missingFields: string[] = [];
  @ViewChild('fileInput') fileInput!: ElementRef<HTMLInputElement>;

  constructor(private svc: CarsService) {}

  ngOnInit() {
    this.svc.getBrands().subscribe(r=> {
      this.brands = (r.data || r).map((b:any)=> ({ ...b, stores: b.stores || [] }));
      this.brandsLoaded = true;
      this.maybeLoadCarAfterData();
    }, err => { console.debug('Falha ao carregar brands', err); this.brandsLoaded = true; this.maybeLoadCarAfterData(); });

    this.svc.getStores().subscribe(r => {
      this.allStores = r.data || r || [];
      this.storesLoaded = true;
      this.maybeLoadCarAfterData();
    }, err => { console.debug('Falha ao carregar stores (getStores)', err); this.storesLoaded = true; this.maybeLoadCarAfterData(); });
  }

  maybeLoadCarAfterData() {
    if (!this.id) return;
    if (!this.brandsLoaded || !this.storesLoaded) return;

    this.svc.getCar(Number(this.id)).subscribe(r=> {
      const car = r.data || r;
      this.form = { ...this.form, ...car };

      try {
        if (car.images) {
          if (typeof car.images === 'string') {
            const parsed = JSON.parse(car.images);
            this.form.images = Array.isArray(parsed) ? parsed : [car.images];
          } else if (Array.isArray(car.images)) {
            this.form.images = car.images;
          } else {
            this.form.images = [String(car.images)];
          }
        } else {
          this.form.images = [];
        }
      } catch (e) {
        this.form.images = typeof car.images === 'string' ? [car.images] : (car.images || []);
      }

      if (car.store) {
        this.form.storeId = car.store.id;
        const brandId = car.store.brand && car.store.brand.id ? car.store.brand.id : (typeof car.store.brand === 'string' || typeof car.store.brand === 'number' ? car.store.brand : null);
        this.form.brandId = brandId ?? this.form.brandId;
        this.filterStoresByBrandId(this.form.brandId);
      }
    }, err => { console.debug('Falha ao carregar car', err); });
  }

  loadStoresByBrand(brandName: string) {
    if (!brandName) { this.stores = []; return; }

    const matched = this.allStores.filter(s => s && s.brand && (s.brand.name === brandName || s.brand === brandName || s.brand?.id == this.form.brandId));
    if (matched.length) { this.stores = matched; return; }
    this.svc.getStoresByBrand(brandName).subscribe(r=> this.stores = r.data || r, err => { console.debug('fallback getStoresByBrand failed', err); this.stores = []; });
  }

  onBrandChange() {
    const brand = this.brands.find(b=> b.id == this.form.brandId);
    this.form.storeId = '';
    this.filterStoresByBrandId(this.form.brandId);
    if ((!this.stores || !this.stores.length) && brand) {
      this.stores = brand.stores || [];
    }
    console.debug('onBrandChange -> brandId, stores count', this.form.brandId, this.stores.length);
  }

  filterStoresByBrandId(brandId: any) {
    if (!brandId) { this.stores = []; return; }

    const filtered = (this.allStores || []).filter((s:any) => {
      if (!s) return false;
      if (s.brand && typeof s.brand === 'object') return s.brand.id == brandId;
      return s.brand == brandId;
    });
    this.stores = filtered;
  }

  onFilesSelected(e: Event) {
    const input = e.target as HTMLInputElement;
    const files = Array.from(input.files || []) as File[];
    if (!this.form.images) this.form.images = [];

    const readers = files.map(f => new Promise<string>((res, rej) => {
      const r = new FileReader();
      r.onload = () => res(String(r.result));
      r.onerror = e => rej(e);
      r.readAsDataURL(f);
    }));
    Promise.all(readers).then(strs => {
      this.form.images = [...this.form.images, ...strs];
    }).catch(err => console.debug('failed to read files', err));
    input.value = '';
  }

  removeImageAt(index: number) {
    this.form.images = (this.form.images || []).filter((_: any, i: number) => i !== index);
  }

  isString(val: any) { return typeof val === 'string'; }

  getObjectURL(file: any) { 
    if (!file) return '';
    if (typeof file === 'string') return file; 
    try { return URL.createObjectURL(file); } catch { return ''; }
  }

  triggerFileDialog() {
    try { this.fileInput.nativeElement.click(); } catch { /* fallback */ }
  }


  onSubmit(carForm: NgForm) {

    try { Object.values(carForm.controls || {}).forEach((c:any) => c.markAsTouched && c.markAsTouched()); } catch {}

    this.missingFields = [];
    this.message = null;

    const requiredChecks: { key: string; label: string }[] = [
      { key: 'brandId', label: 'Marca' },
      { key: 'storeId', label: 'Loja' },
      { key: 'model', label: 'Modelo' },
      { key: 'version', label: 'Versão' },
      { key: 'year', label: 'Ano' },
      { key: 'mileage', label: 'Quilometragem' },
      { key: 'price', label: 'Valor' }
    ];

    for (const c of requiredChecks) {
      const val = this.form[c.key];
      const empty = val === null || val === undefined || String(val).trim() === '';
      if (empty) this.missingFields.push(c.label);
    }

    if (this.missingFields.length) {
      this.message = `Preencha os campos obrigatórios: ${this.missingFields.join(', ')}`;
    
      setTimeout(() => { this.message = null; this.missingFields = []; }, 5000);
      return;
    }

   
    this.submit();
  }

  submit() {
    this.loading = true;
    const payload = { ...this.form };
    if (this.id) {
      this.svc.updateCar(Number(this.id), payload).subscribe(()=> {
        this.message = 'Edição realizada com sucesso !!'; this.onSaved.emit(); this.onMessage.emit({ type: 'success', text: 'Edição realizada com sucesso' }); setTimeout(()=> this.onClose.emit(),800)
      }, (err:any)=> {
        const text = err?.error?.message || err?.message || 'Falha';
        this.message = text; this.onMessage.emit({ type: 'error', text }); this.loading = false;
      })
    } else {
      this.svc.createCar(payload).subscribe(()=> {
        this.message='Cadastro concluído com sucesso !!'; this.onSaved.emit(); this.onMessage.emit({ type: 'success', text: 'Cadastro concluído' }); setTimeout(()=> this.onClose.emit(),800)
      }, (err:any)=> {
        const text = err?.error?.message || err?.message || 'Falha';
        this.message = text; this.onMessage.emit({ type: 'error', text }); this.loading = false;
      })
    }
  }

  remove() {
    if (!this.id) return;
    if (!confirm('Confirma exclusão?')) return;
    this.svc.deleteCar(Number(this.id)).subscribe(()=> { this.message='Exclusão realizada'; this.onSaved.emit(); this.onMessage.emit({ type: 'success', text: 'Exclusão realizada com sucesso !! ' }); setTimeout(()=> this.onClose.emit(),800) }, (err:any)=> { const text = err?.error?.message || err?.message || 'Falha'; this.onMessage.emit({ type: 'error', text }); })
  }
}


<div class="modal-overlay">
  <div class="card">

    <div *ngIf="missingFields?.length" class="error-banner" style="margin-bottom:12px;padding:10px;border-radius:8px;background:#ffecec;color:#a40000;">
      Preencha os campos obrigatórios: {{ missingFields.join(', ') }}
    </div>


    <div *ngIf="message" class="result-modal" style="margin-bottom:12px;padding:10px;border-radius:8px;background:#f0f6ff;color:#073763;">
      {{ message }}
    </div>

    <form #carForm="ngForm" (ngSubmit)="onSubmit(carForm)" class="form-column" novalidate>
      <div class="field">
        <label>Marca</label>
        <select [(ngModel)]="form.brandId" name="brandId" (change)="onBrandChange()" required>
          <option value="">Selecione a marca</option>
          <option *ngFor="let b of brands" [value]="b.id">{{ b.name }}</option>
        </select>
      </div>

      <div class="field">
        <label>Loja</label>
        <select [(ngModel)]="form.storeId" name="storeId" required>
          <option value="">Selecione a loja</option>
          <option *ngFor="let s of stores" [value]="s.id">{{ s.name }}</option>
        </select>
        <small *ngIf="(!stores || stores.length === 0)" class="help">Nenhuma loja disponível para a marca selecionada.</small>
      </div>

      <div class="field">
        <label>Modelo</label>
        <input [(ngModel)]="form.model" name="model" placeholder="Informe o modelo" required />
      </div>

      <div class="field">
        <label>Versão</label>
        <input [(ngModel)]="form.version" name="version" placeholder="Informe a versão" required />
      </div>

    <div class="field">
        <label>Ano Fabricação/Modelo</label>
        <input type="text" [(ngModel)]="form.year" name="year" placeholder="Ex: 2018 ou 2018/2019" required />
      </div>

      <div class="field">
        <label>Quilometragem</label>
        <input type="number" [(ngModel)]="form.mileage" name="mileage" placeholder="Informe a quilometragem" required />
      </div>

      <div class="field">
        <label>Valor</label>
        <input type="number" [(ngModel)]="form.price" name="price" step="0.01" placeholder="Informe o valor" required />
      </div>

      <div class="field">
        <label>Descrição</label>
        <textarea [(ngModel)]="form.description" name="description" rows="3" placeholder="Digite a descrição do veículo"></textarea>
      </div>

      <div class="field">
        <label>Upload imagens</label>
        <div class="upload-area" (drop)="$event.preventDefault()" (dragover)="$event.preventDefault()">
          <div class="thumbs">
            <div *ngFor="let it of (form.images || []); let i = index" class="thumb">
              <img [src]="isString(it) ? it : getObjectURL(it)" [alt]="'img-'+i" />
              <button type="button" class="remove" (click)="removeImageAt(i)">✕</button>
            </div>
            <div class="thumb add" (click)="triggerFileDialog()">
              <div class="plus">+</div>
            </div>
          </div>
          <input #fileInput type="file" multiple style="display:none" (change)="onFilesSelected($event)" />
        </div>
      </div>

      <div class="footer-actions" style="display:flex;justify-content:space-between;align-items:center;margin-top:16px;">
        <div>
          <button *ngIf="id" type="button" class="btn danger" (click)="remove()" [disabled]="loading">Excluir</button>
        </div>

        <div style="display:flex;gap:12px;">
          <button type="button" class="btn cancel" (click)="onClose.emit()" [disabled]="loading">Cancelar</button>
          <button class="btn save" type="submit" [disabled]="loading">
            <span *ngIf="loading">Salvando...</span>
            <span *ngIf="!loading">Salvar</span>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
